### ISSUE TITLE
Missing folder \potions\ in the path. 

### ISSUE THREAD

**Issue by xkhainedx** [Deatho0ne/IdleChamp-Deatho0ne#22]
https://github.com/Deatho0ne/IdleChamp-Deatho0ne/blob/fb6dd345e7d1c60e7ed72e2c3ae142abfec8fe32/MadWizard/GemFarmMod.ahk#L209

**Comment by Deatho0ne** [comment]
Really just need to remove it from the code, but sort of lazy. Basically it came from someone else's work and I have just not removed it. They really could not get it to work since the potions have gradient overlay on them that changes with time.

**Comment by Deatho0ne** [comment]
Actually got right of it due to the above.
